package ru.sfedu.Aisova;

public class Constants {
    static public final String SPLIT =",";
    static public final String LIST_START_SYMBOL ="[";
    static public final String LIST_END_SYMBOL ="]";
    static public final String PEOPLE_START_SYMBOL ="{";
    static public final String PEOPLE_END_SYMBOL ="}";
    public static final String CANNOT_CREATE_FILE = "config.path";
    public static final String CONFIG_PATH = "config.path";
    public static final String PATH_CSV = "csv_path";
    public static final String FILE_EXTENSION_CSV = "csv";
    public static final String PATH_XML = "xml_path";
    public static final String FILE_EXTENSION_XML = "xml";
    public static final String WRITE_SUCCESS = "Write success";
    public static final String WRITE_ERROR = "Write error";
    public static final String STH_NULL = "Something is null";
    public static final String READ_SUCCESS = "Read success";
    public static final String READ_ERROR = "Read error";
    public static final String NULL_VALUE = "Null value. No entry added";
    public static final String NOT_FOUND = " not found";
    public static final String SERVICE_CREATED = "Service created";
    public static final String SERVICE_NOT_CREATED = "Service not created";
    public static final String SERVICE_ID = "Service with id = ";
    public static final String SERVICE_EDITED = "Service edited";
    public static final String SERVICE_NOT_EDITED = "Service not edited";
    public static final String SERVICE_DELETED = "Service deleted";
    public static final String SERVICE_NOT_DELETED = "Service not deleted";
    public static final String SERVICE_RECEIVED = "Service received";
    public static final String SERVICE_NOT_RECEIVED = "Service not received";
    public static final String NEW_CUSTOMER_CREATED = "New customer created";
    public static final String NEW_CUSTOMER_NOT_CREATED = "New customer not created";
    public static final String NEW_CUSTOMER_ID = "New customer with id = ";
    public static final String NEW_CUSTOMER_EDITED = "New customer edited";
    public static final String NEW_CUSTOMER_NOT_EDITED = "New customer not edited";
    public static final String NEW_CUSTOMER_DELETED = "New customer deleted";
    public static final String NEW_CUSTOMER_NOT_DELETED = "New customer not deleted";
    public static final String NEW_CUSTOMER_RECEIVED = "New customer received";
    public static final String NEW_CUSTOMER_NOT_RECEIVED = "New customer not received";
    public static final String REGULAR_CUSTOMER_CREATED = "Regular customer created";
    public static final String REGULAR_CUSTOMER_NOT_CREATED = "Regular customer not created";
    public static final String REGULAR_CUSTOMER_ID = "Regular customer with id = ";
    public static final String REGULAR_CUSTOMER_EDITED = "Regular customer edited";
    public static final String REGULAR_CUSTOMER_NOT_EDITED = "Regular customer not edited";
    public static final String REGULAR_CUSTOMER_DELETED = "Regular customer deleted";
    public static final String REGULAR_CUSTOMER_NOT_DELETED = "Regular customer not deleted";
    public static final String REGULAR_CUSTOMER_RECEIVED = "Regular customer received";
    public static final String REGULAR_CUSTOMER_NOT_RECEIVED = "Regular customer not received";
    public static final String MASTER_CREATED = "Master created";
    public static final String MASTER_NOT_CREATED = "Master not created";
    public static final String MASTER_ID = "Master with id = ";
    public static final String MASTER_EDITED = "Master edited";
    public static final String MASTER_NOT_EDITED = "Master not edited";
    public static final String MASTER_DELETED = "Master deleted";
    public static final String MASTER_NOT_DELETED = "Master not deleted";
    public static final String MASTER_RECEIVED = "Master received";
    public static final String MASTER_NOT_RECEIVED = "Master not received";
    public static final String SALON_CREATED = "Salon created";
    public static final String SALON_NOT_CREATED = "Salon not created";
    public static final String SALON_ID = "Salon with id = ";
    public static final String SALON_EDITED = "Salon edited";
    public static final String SALON_NOT_EDITED = "Salon not edited";
    public static final String SALON_DELETED = "Salon deleted";
    public static final String SALON_NOT_DELETED = "Salon not deleted";
    public static final String SALON_RECEIVED = "Salon received";
    public static final String SALON_NOT_RECEIVED = "Salon not received";
    public static final String ORDER_ITEM_CREATED = "Order item created";
    public static final String ORDER_ITEM_NOT_CREATED = "Order item not created";
    public static final String ORDER_ITEM_ID = "Order item with id = ";
    public static final String ORDER_ITEM_EDITED = "Order item edited";
    public static final String ORDER_ITEM_NOT_EDITED = "Order item not edited";
    public static final String ORDER_ITEM_DELETED = "Order item deleted";
    public static final String ORDER_ITEM_NOT_DELETED = "Order item not deleted";
    public static final String ORDER_ITEM_RECEIVED = "Order item received";
    public static final String ORDER_ITEM_NOT_RECEIVED = "Order item not received";
    public static final String ORDER_CREATED = "Order created";
    public static final String ORDER_NOT_CREATED = "Order not created";
    public static final String ORDER_ID = "Order with id = ";
    public static final String ORDER_EDITED = "Order edited";
    public static final String ORDER_NOT_EDITED = "Order not edited";
    public static final String ORDER_DELETED = "Order deleted";
    public static final String ORDER_NOT_DELETED = "Order not deleted";
    public static final String ORDER_RECEIVED = "Order received";
    public static final String ORDER_NOT_RECEIVED = "Order not received";
    public static final String ORDER_COST = "Order cost ";
    public static final String EQL = " = ";
    public static final String CUSTOMER_ID = "Customer with id = ";
    public static final String LIST_CUSTOMER = "Order list customer ";
    public static final String COLON = ":";
    public static final String PROCESSING ="PROCESSING";
    public static final String CURRENT_ORDER = "Current orders list customer ";
    public static final String NOT_CURRENT_ORDER ="The order is not current";
    public static final String NUM_CUSTOMER ="Number of customer ";
    public static final String ORDER_EQL = " orders = ";
    public static final String LIST_MASTER = "Master list in salon ";
    public static final String ASSIGN_SUCCESS ="Service assign success";
    public static final String ASSIGN_FAIL ="Service assign fail";
    public static final String MASTER ="Master ";
    public static final String PROVIDE_SERVICE =" provides the following service: ";


}
